#!/bin/bash

set -e

scriptdir=$(dirname "${BASH_SOURCE[0]}")

execTest()
{
	local line="$1"; shift
	local exitCode="$1"; shift
	local config=--config="$scriptdir/mkcert-ca-complete.conf.json"
	local result

	[[ $RMDIRS =~ etc ]] && rm -rf "$scriptdir/etc"
	[[ $RMDIRS =~ tmp ]] && rm -rf "$scriptdir/tmp"

	if [[ $CHMOD ]]; then
		chmod 600 \
			"$scriptdir/etc/ssl/CA/"*"/private/"*".key"* \
			"$scriptdir/etc/ssl/private/"*".key"*
	fi

	status=0
	result=$("$scriptdir/mkcert-ca-complete.sh" $config --verbose "$@" 2>&1) || status=$?

	if [[ $status != $exitCode ]]; then
		echo -e "\033[1;31mFAILED:$line\033[m '$scriptdir/mkcert-ca-complete.sh' $config --verbose $@"
		echo -e "\033[1;31m\$?=$status (expected $exitCode)\n$result\033[m"

		return 1
	else
		if result=$(diff -u - <(echo "$result")); then
			echo -e "\033[32mPASSED:$line\033[m"
		else
			echo -e "\033[1;31mFAILED:$line\033[m '$scriptdir/mkcert-ca-complete.sh' $config --verbose $@"

			sed -e '/^---/d; /^+++/d' \
				-e $'s/^-.*$/\033[31m&\033[m/g' \
				-e $'s/^+.*$/\033[33m&\033[m/g' \
				-e $'s/^@@.*@@$/\033[36m&\033[m/g' <<< "$result"

			return 1
		fi
	fi
}

# no certificate; nothing to do, no error

RMDIRS=etc,tmp \
execTest $LINENO 0 <<< ""

# try creating user certificate without intermediate cert

RMDIRS=etc,tmp \
execTest $LINENO 3 localhost <<"EOF"
[37;1mChecking for CA certificate:[m
  [31mca-intermediate certificate not found.[m
EOF

# try creating intermediate and user certificate without root cert

RMDIRS=etc,tmp \
execTest $LINENO 3 --genpkey=ca-intermediate localhost <<"EOF"
[37;1mChecking for CA certificate:[m
  [31mca-root certificate not found.[m
EOF

# create complete chain, no pkeys yet -> will be created automatically

RMDIRS=etc,tmp \
execTest $LINENO 0 ca-root ca-intermediate localhost <<"EOF"
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/root/private/ca-root.key.enc -pass stdin
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssl/openssl.cnf -utf8 -out etc/ssl/CA/root/certs/ca-root.crt -key etc/ssl/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -pass stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/root/csr/ca-intermediate.csr -key etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssl/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/root/certs/ca-root.crt etc/ssl/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_root -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -aes-256-cbc -out etc/ssl//private/localhost.key.enc -pass stdin
/usr/bin/openssl rsa -in etc/ssl//private/localhost.key.enc -out etc/ssl//private/localhost.key -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/intermediate/csr/localhost.csr -key etc/ssl//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl//certs/localhost.crt -infiles etc/ssl/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/intermediate/certs/ca-intermediate.crt etc/ssl//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_default -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# create complete chain, re-create all private keys
CHMOD=keys \
execTest $LINENO 0 --genpkey=ca-root,ca-intermediate,localhost <<"EOF"
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/root/private/ca-root.key.enc -pass stdin
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssl/openssl.cnf -utf8 -out etc/ssl/CA/root/certs/ca-root.crt -key etc/ssl/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -pass stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/root/csr/ca-intermediate.csr -key etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssl/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/root/certs/ca-root.crt etc/ssl/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_root -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -aes-256-cbc -out etc/ssl//private/localhost.key.enc -pass stdin
/usr/bin/openssl rsa -in etc/ssl//private/localhost.key.enc -out etc/ssl//private/localhost.key -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/intermediate/csr/localhost.csr -key etc/ssl//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl//certs/localhost.crt -infiles etc/ssl/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/intermediate/certs/ca-intermediate.crt etc/ssl//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_default -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# create complete chain, re-create all private keys, use --separator

CHMOD=keys \
execTest $LINENO 0 --separator=' ' --genpkey='ca-root ca-intermediate localhost' <<"EOF"
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/root/private/ca-root.key.enc -pass stdin
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssl/openssl.cnf -utf8 -out etc/ssl/CA/root/certs/ca-root.crt -key etc/ssl/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -pass stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/root/csr/ca-intermediate.csr -key etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssl/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/root/certs/ca-root.crt etc/ssl/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_root -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -aes-256-cbc -out etc/ssl//private/localhost.key.enc -pass stdin
/usr/bin/openssl rsa -in etc/ssl//private/localhost.key.enc -out etc/ssl//private/localhost.key -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/intermediate/csr/localhost.csr -key etc/ssl//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl//certs/localhost.crt -infiles etc/ssl/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/intermediate/certs/ca-intermediate.crt etc/ssl//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_default -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# create complete chain with existing keys

execTest $LINENO 0 ca-root ca-intermediate localhost <<"EOF"
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssl/openssl.cnf -utf8 -out etc/ssl/CA/root/certs/ca-root.crt -key etc/ssl/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/root/csr/ca-intermediate.csr -key etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssl/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/root/certs/ca-root.crt etc/ssl/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_root -cert etc/ssl/CA/root/certs/ca-root.crt -keyfile etc/ssl/CA/root/private/ca-root.key.enc -out etc/ssl/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/intermediate/csr/localhost.csr -key etc/ssl//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl//certs/localhost.crt -infiles etc/ssl/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/intermediate/certs/ca-intermediate.crt etc/ssl//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_default -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# create user cert only

execTest $LINENO 0 localhost <<"EOF"
/usr/bin/openssl req -new -utf8 -config etc/ssl/openssl.cnf -out etc/ssl/CA/intermediate/csr/localhost.csr -key etc/ssl//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssl/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl//certs/localhost.crt -infiles etc/ssl/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssl/CA/intermediate/certs/ca-intermediate.crt etc/ssl//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssl/openssl.cnf -name CA_default -cert etc/ssl/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssl/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssl/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# "forget" to create CAs

RMDIRS=etc,tmp \
execTest $LINENO 3 localhost <<"EOF"
[37;1mChecking for CA certificate:[m
  [31mca-intermediate certificate not found.[m
EOF

# "forget" to create root CA

execTest $LINENO 3 --genpkey=ca-intermediate,localhost <<"EOF"
[37;1mChecking for CA certificate:[m
  [31mca-root certificate not found.[m
EOF

# Use ssldir containing spaces

execTest $LINENO 0 --ssldir="etc/ssldir with spaces" ca-root ca-intermediate localhost <<"EOF"
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssldir\ with\ spaces/CA/root/private/ca-root.key.enc -pass stdin
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssldir\ with\ spaces/openssl.cnf -utf8 -out etc/ssldir\ with\ spaces/CA/root/certs/ca-root.crt -key etc/ssldir\ with\ spaces/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssldir\ with\ spaces/CA/intermediate/private/ca-intermediate.key.enc -pass stdin
/usr/bin/openssl req -new -utf8 -config etc/ssldir\ with\ spaces/openssl.cnf -out etc/ssldir\ with\ spaces/CA/root/csr/ca-intermediate.csr -key etc/ssldir\ with\ spaces/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssldir\ with\ spaces/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssldir\ with\ spaces/CA/root/certs/ca-root.crt -keyfile etc/ssldir\ with\ spaces/CA/root/private/ca-root.key.enc -out etc/ssldir\ with\ spaces/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssldir\ with\ spaces/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssldir\ with\ spaces/CA/root/certs/ca-root.crt etc/ssldir\ with\ spaces/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssldir\ with\ spaces/openssl.cnf -name CA_root -cert etc/ssldir\ with\ spaces/CA/root/certs/ca-root.crt -keyfile etc/ssldir\ with\ spaces/CA/root/private/ca-root.key.enc -out etc/ssldir\ with\ spaces/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -aes-256-cbc -out etc/ssldir\ with\ spaces//private/localhost.key.enc -pass stdin
/usr/bin/openssl rsa -in etc/ssldir\ with\ spaces//private/localhost.key.enc -out etc/ssldir\ with\ spaces//private/localhost.key -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssldir\ with\ spaces/openssl.cnf -out etc/ssldir\ with\ spaces/CA/intermediate/csr/localhost.csr -key etc/ssldir\ with\ spaces//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssldir\ with\ spaces/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssldir\ with\ spaces/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssldir\ with\ spaces/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssldir\ with\ spaces//certs/localhost.crt -infiles etc/ssldir\ with\ spaces/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssldir\ with\ spaces/CA/intermediate/certs/ca-intermediate.crt etc/ssldir\ with\ spaces//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssldir\ with\ spaces/openssl.cnf -name CA_default -cert etc/ssldir\ with\ spaces/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssldir\ with\ spaces/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssldir\ with\ spaces/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF

# Use ssldir from JSON

mkdir -p "$scriptdir/etc"
jq '.ssldir="etc/ssldir from json"' mkcert-ca-complete.conf.json > "$scriptdir/etc/mkcert.json"

execTest $LINENO 0 --config="$scriptdir/etc/mkcert.json" ca-root ca-intermediate localhost <<"EOF"
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssldir\ from\ json/CA/root/private/ca-root.key.enc -pass stdin
/usr/bin/openssl req -new -x509 -extensions v3_ca -sha512 -days 9125 -config etc/ssldir\ from\ json/openssl.cnf -utf8 -out etc/ssldir\ from\ json/CA/root/certs/ca-root.crt -key etc/ssldir\ from\ json/CA/root/private/ca-root.key.enc -subj /C=\?\?/L=City/O=organisation/CN=ca-root-name -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:8192 -aes-256-cbc -out etc/ssldir\ from\ json/CA/intermediate/private/ca-intermediate.key.enc -pass stdin
/usr/bin/openssl req -new -utf8 -config etc/ssldir\ from\ json/openssl.cnf -out etc/ssldir\ from\ json/CA/root/csr/ca-intermediate.csr -key etc/ssldir\ from\ json/CA/intermediate/private/ca-intermediate.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=ca-intermediate-name -passin stdin
/usr/bin/openssl ca -config etc/ssldir\ from\ json/openssl.cnf -name CA_root -extensions v3_intermediate_ca -notext -batch -passin stdin -cert etc/ssldir\ from\ json/CA/root/certs/ca-root.crt -keyfile etc/ssldir\ from\ json/CA/root/private/ca-root.key.enc -out etc/ssldir\ from\ json/CA/intermediate/certs/ca-intermediate.crt -infiles etc/ssldir\ from\ json/CA/root/csr/ca-intermediate.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssldir\ from\ json/CA/root/certs/ca-root.crt etc/ssldir\ from\ json/CA/intermediate/certs/ca-intermediate.crt
/usr/bin/openssl ca -gencrl -config etc/ssldir\ from\ json/openssl.cnf -name CA_root -cert etc/ssldir\ from\ json/CA/root/certs/ca-root.crt -keyfile etc/ssldir\ from\ json/CA/root/private/ca-root.key.enc -out etc/ssldir\ from\ json/CA/root/revoked/ca-root.crl -passin stdin
/usr/bin/openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:4096 -aes-256-cbc -out etc/ssldir\ from\ json//private/localhost.key.enc -pass stdin
/usr/bin/openssl rsa -in etc/ssldir\ from\ json//private/localhost.key.enc -out etc/ssldir\ from\ json//private/localhost.key -passin stdin
/usr/bin/openssl req -new -utf8 -config etc/ssldir\ from\ json/openssl.cnf -out etc/ssldir\ from\ json/CA/intermediate/csr/localhost.csr -key etc/ssldir\ from\ json//private/localhost.key.enc -subj /C=\?\?/L=City/O=organisation/OU=unit/CN=localhost -passin stdin
/usr/bin/openssl ca -config etc/ssldir\ from\ json/openssl.cnf -name CA_default -extensions usr_cert -notext -batch -passin stdin -cert etc/ssldir\ from\ json/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssldir\ from\ json/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssldir\ from\ json//certs/localhost.crt -infiles etc/ssldir\ from\ json/CA/intermediate/csr/localhost.csr
/usr/bin/openssl verify -partial_chain -CAfile etc/ssldir\ from\ json/CA/intermediate/certs/ca-intermediate.crt etc/ssldir\ from\ json//certs/localhost.crt
/usr/bin/openssl ca -gencrl -config etc/ssldir\ from\ json/openssl.cnf -name CA_default -cert etc/ssldir\ from\ json/CA/intermediate/certs/ca-intermediate.crt -keyfile etc/ssldir\ from\ json/CA/intermediate/private/ca-intermediate.key.enc -out etc/ssldir\ from\ json/CA/intermediate/revoked/ca-intermediate.crl -passin stdin
EOF
